/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'



export function Snowflake03(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/snowflake03.glb')
  const { actions } = useAnimations<GLTFActions>(animations, group)

  useEffect(() => {
    console.log('actions', actions)
    actions["SnowflakeAction.001"]?.play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Snowflake" geometry={nodes.Snowflake.geometry} material={materials['Ice Imperfections']} rotation={[0, -0.77, 0.26]} />
      </group>
    </group>
  )
}

useGLTF.preload('/snowflake03.glb')
